set(CORECRYPTO_ccmode_PUBLIC_HEADERS
    corecrypto/ccmode.h
    corecrypto/ccmode_factory.h
    corecrypto/ccmode_impl.h
)

set(CORECRYPTO_ccmode_SOURCES
    cbc/cccbc_block_size.c
    cbc/cccbc_context_size.c
    cbc/cccbc_init.c
    cbc/cccbc_one_shot.c
    cbc/cccbc_set_iv.c
    cbc/cccbc_update.c
    cbc/ccmode_cbc_decrypt.c
    cbc/ccmode_cbc_encrypt.c
    cbc/ccmode_cbc_init.c
    cbc/ccmode_factory_cbc_decrypt.c
    cbc/ccmode_factory_cbc_encrypt.c
    ctr/ccctr_block_size.c
    ctr/ccctr_context_size.c
    ctr/ccctr_init.c
    ctr/ccctr_one_shot.c
    ctr/ccctr_setctr.c
    ctr/ccctr_update.c
    ctr/ccmode_ctr_crypt.c
    ctr/ccmode_ctr_init.c
    ctr/ccmode_ctr_setctr.c
    ctr/ccmode_factory_ctr_crypt.c
    ecb/ccecb_block_size.c
    ecb/ccecb_context_size.c
    ecb/ccecb_init.c
    ecb/ccecb_one_shot.c
    ecb/ccecb_update.c
)